"""0.15.0: the REFramework research build (online Lua for the sf6bot exporter only, until the research period ends).
The C++ patch itself is checked on REFramework's real source when the workflow builds; here: the patch script's
edits on minimal stand-ins of the three upstream files, and the bot-side status / install / restore."""
import importlib.util
import zipfile
from pathlib import Path

import pytest

from sf6bot import refw_research as rr
from sf6bot.game_state import LUA_SRC

ROOT = Path(__file__).parent.parent


def _patcher():
    spec = importlib.util.spec_from_file_location("patch", ROOT / "tools" / "refw_research_patch.py")
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def _fake_refw(tmp_path):
    """The exact upstream lines the patch edits (praydog/REFramework d1461375), in minimal files."""
    sdk = tmp_path / "shared" / "sdk"
    sdk.mkdir(parents=True)
    (sdk / "SF6Utility.cpp").write_text('#include "SF6Utility.hpp"\n\nnamespace sdk {\nnamespace sf6 {\n'
                                        "bool is_online_match() {\n    return true;\n}\n}\n}\n")
    (sdk / "SF6Utility.hpp").write_text("#pragma once\n\n#include <optional>\n\nbool is_online_match();\n")
    mods = tmp_path / "src" / "mods"
    mods.mkdir(parents=True)
    (mods / "ScriptRunner.cpp").write_text(
        "void ScriptState::run_script(const std::string& p) {\n}\n"
        "                this->set_last_online_match_state();\n"
        "    if (ImGui::CollapsingHeader(get_name().data())) {\n        if (m_last_online_match_state) {\n")
    return tmp_path


def test_patch_edits_each_upstream_spot_once_and_embeds_the_exact_exporter(tmp_path):
    p = _patcher()
    refw = _fake_refw(tmp_path)
    info = p.patch(refw, "2033-10-01", LUA_SRC)
    assert info["marker"] == f"SF6BOT-RESEARCH-BUILD until=2033-10-01 exporter={rr.exporter_id(LUA_SRC.read_bytes())}"
    cpp = (refw / "shared/sdk/SF6Utility.cpp").read_text()
    assert "if (sf6bot_research_window()) {\n        return false;" in cpp
    sr = (refw / "src/mods/ScriptRunner.cpp").read_text()
    assert "!sdk::sf6::is_sf6bot_exporter(p)" in sr and "if (!sdk::sf6::sf6bot_research_window())" in sr
    hdr = (refw / "shared/sdk/Sf6botResearch.autogenerated.hpp").read_text()
    size = len(LUA_SRC.read_bytes().replace(b"\r", b""))
    assert f"SF6BOT_EXPORTER_SIZE = {size};" in hdr
    with pytest.raises(SystemExit):                  # applying twice: upstream text no longer matches once
        p.patch(refw, "2033-10-01", LUA_SRC)


def test_status_install_restore(tmp_path):
    game = tmp_path / "SF6"
    game.mkdir()
    (game / "dinput8.dll").write_bytes(b"MZ official reframework")
    st = rr.status(game)
    assert st["dll"]["kind"] == "official" and "OFF in online matches" in " ".join(rr.describe(st))
    marker = f"SF6BOT-RESEARCH-BUILD until=2033-10-01 exporter={rr.exporter_id(LUA_SRC.read_bytes())}".encode()
    z = tmp_path / "sf6bot-refw-research.zip"
    with zipfile.ZipFile(z, "w") as f:
        f.writestr("dinput8.dll", b"MZ research \x00" + marker + b"\x00")
        f.writestr("BUILD_INFO.txt", "x")
    with pytest.raises(RuntimeError):
        rr.install(game, z, game_running=True)          # Windows locks the dll while SF6 runs
    msgs = rr.install(game, z, game_running=False)
    assert any("Kept the official" in m for m in msgs) and any("exact file" in m for m in msgs)
    st = rr.status(game)
    assert st["dll"] == {"kind": "research", "until": "2033-10-01", "exporter": rr.exporter_id(LUA_SRC.read_bytes()),
                         "online_lua": True}
    assert st["exporter_matches_build"] and st["backup_of_official"]
    assert "active now" in " ".join(rr.describe(st))
    rr.install(game, z, game_running=False)              # a second install keeps the ORIGINAL official backup
    assert (game / "dinput8.dll.official").read_bytes() == b"MZ official reframework"
    rr.restore(game, game_running=False)
    assert rr.status(game)["dll"]["kind"] == "official"
    bad = tmp_path / "other.dll"
    bad.write_bytes(b"MZ something else")
    with pytest.raises(ValueError):
        rr.install(game, bad, game_running=False)        # only the research build is accepted


def test_expired_build_says_so():
    d = rr.dll_info(b"xx SF6BOT-RESEARCH-BUILD until=2020-01-01 exporter=0123456789abcdef xx")
    assert d["kind"] == "research" and d["online_lua"] is False


def test_the_bundled_build_runs_the_current_exporter():
    """refw_research/dist holds the GitHub build (brought by update.bat). The research build runs only the exporter it
    was built with: a changed sf6bot_state.lua needs a new build copied there, or the bot is blind online."""
    z = rr.find_zip()
    assert z == rr.BUNDLED and z.exists()
    data = zipfile.ZipFile(z).read("dinput8.dll")
    assert rr.dll_info(data)["exporter"] == rr.exporter_id(LUA_SRC.read_bytes())
