"""Patch a praydog/REFramework checkout into the sf6bot research build (used by
.github/workflows/refw-research-build.yml; can be run by hand on any checkout).

Why: stock REFramework unloads every Lua script during online SF6 matches (ScriptRunner + sdk::sf6::is_online_match),
so the bot's state exporter is blind in ranked. Capcom approved, in writing (2026-10-03, to the user), REFramework
functioning in online matches for the agreed research period, for the disclosed CFN.

What the patch does, and nothing else:
  1. Until the end of the research period (UTC, compiled in), sdk::sf6::is_online_match() reports "not online", so
     ScriptRunner keeps Lua running in online matches. After that date the stock behaviour is back by itself.
  2. While that window is open, ScriptState::run_script() runs ONLY the sf6bot state exporter: a file whose bytes
     (line endings ignored) equal reframework/autorun/sf6bot_state.lua at build time, embedded in the DLL. Every
     other script (autorun or "Run script") is skipped and logged. So the build cannot run other Lua online.
  3. The REFramework window states this (ScriptRunner section), and the DLL carries a marker string that
     `sf6bot refw-research status` reads: "SF6BOT-RESEARCH-BUILD until=YYYY-MM-DD exporter=<sha256 prefix>".

Every edit must match the upstream source exactly once, or the patch stops with an error (upstream changed:
review before building).

usage: python tools/refw_research_patch.py <refw checkout> <until YYYY-MM-DD> <exporter.lua>
"""
from __future__ import annotations

import datetime as dt
import hashlib
import sys
from pathlib import Path

MARKER = "SF6BOT-RESEARCH-BUILD"


def exporter_bytes(lua: Path) -> bytes:
    return lua.read_bytes().replace(b"\r", b"")


def exporter_id(lua: Path) -> str:
    return hashlib.sha256(exporter_bytes(lua)).hexdigest()[:16]


def _once(text: str, old: str, new: str, where: str) -> str:
    n = text.count(old)
    if n != 1:
        raise SystemExit(f"patch: expected exactly one match in {where}, found {n}:\n{old}")
    return text.replace(old, new)


def patch(refw: Path, until: str, lua: Path) -> dict:
    day = dt.date.fromisoformat(until)
    epoch = int(dt.datetime(day.year, day.month, day.day, tzinfo=dt.timezone.utc).timestamp())
    data = exporter_bytes(lua)
    marker = f"{MARKER} until={day.isoformat()} exporter={exporter_id(lua)}"

    # generated header: the exporter's bytes (an array, not a string literal: MSVC limits literal length)
    hdr = refw / "shared" / "sdk" / "Sf6botResearch.autogenerated.hpp"
    rows = [", ".join(str(b) for b in data[i:i + 32]) for i in range(0, len(data), 32)]
    hdr.write_text(
        "// Generated by sf6bot tools/refw_research_patch.py: the sf6bot state exporter this build allows.\n"
        "#pragma once\n#include <cstddef>\n\n"
        f"static constexpr long long SF6BOT_RESEARCH_UNTIL = {epoch}LL;  // {day.isoformat()} 00:00 UTC\n"
        f"static constexpr const char* SF6BOT_RESEARCH_MARKER = \"{marker}\";\n"
        f"static constexpr std::size_t SF6BOT_EXPORTER_SIZE = {len(data)};\n"
        "static constexpr unsigned char SF6BOT_EXPORTER[] = {\n" + ",\n".join(rows) + "\n};\n",
        encoding="utf-8")

    # 1. SF6Utility: the research window, and is_online_match() inside it
    cpp = refw / "shared" / "sdk" / "SF6Utility.cpp"
    s = cpp.read_text(encoding="utf-8")
    s = _once(s, '#include "SF6Utility.hpp"\n',
              '#include "SF6Utility.hpp"\n#include "Sf6botResearch.autogenerated.hpp"\n\n#include <algorithm>\n'
              '#include <cstring>\n#include <ctime>\n#include <fstream>\n#include <iterator>\n', "SF6Utility.cpp includes")
    s = _once(s, "bool is_online_match() {\n",
              "// sf6bot research build: the end of the research period Capcom approved (compiled in). Inside it, Lua\n"
              "// keeps running in online matches (but only the sf6bot exporter runs at all: is_sf6bot_exporter).\n"
              "bool sf6bot_research_window() {\n"
              "    return (long long)std::time(nullptr) < SF6BOT_RESEARCH_UNTIL;\n"
              "}\n\n"
              "const char* sf6bot_research_text() {\n"
              "    return SF6BOT_RESEARCH_MARKER;\n"
              "}\n\n"
              "bool is_sf6bot_exporter(const std::string& path) {\n"
              "    std::ifstream f(path, std::ios::binary);\n"
              "    if (!f) {\n"
              "        return false;\n"
              "    }\n"
              "    std::string s((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());\n"
              "    s.erase(std::remove(s.begin(), s.end(), '\\r'), s.end());\n"
              "    return s.size() == SF6BOT_EXPORTER_SIZE && std::memcmp(s.data(), SF6BOT_EXPORTER, s.size()) == 0;\n"
              "}\n\n"
              "bool is_online_match() {\n"
              "    if (sf6bot_research_window()) {\n"
              "        return false;\n"
              "    }\n\n", "is_online_match")
    cpp.write_text(s, encoding="utf-8")

    h = refw / "shared" / "sdk" / "SF6Utility.hpp"
    s = h.read_text(encoding="utf-8")
    s = _once(s, "bool is_online_match();\n",
              "bool is_online_match();\nbool sf6bot_research_window();\nconst char* sf6bot_research_text();\n"
              "bool is_sf6bot_exporter(const std::string& path);\n", "SF6Utility.hpp")
    if "#include <string>" not in s:
        s = _once(s, "#pragma once\n", "#pragma once\n\n#include <string>\n", "SF6Utility.hpp pragma")
    h.write_text(s, encoding="utf-8")

    # 2. ScriptRunner: the network-mode hook must not force "online" inside the window; only the exporter runs
    sr = refw / "src" / "mods" / "ScriptRunner.cpp"
    s = sr.read_text(encoding="utf-8")
    s = _once(s, "                this->set_last_online_match_state();\n",
              "                if (!sdk::sf6::sf6bot_research_window()) {\n"
              "                    this->set_last_online_match_state();\n"
              "                }\n", "ScriptRunner set_last_online_match_state")
    s = _once(s, "void ScriptState::run_script(const std::string& p) {\n",
              "void ScriptState::run_script(const std::string& p) {\n"
              "    if (sdk::sf6::sf6bot_research_window() && !sdk::sf6::is_sf6bot_exporter(p)) {\n"
              "        spdlog::info(\"[ScriptState] sf6bot research build: not running {} (only the sf6bot state \"\n"
              "                     \"exporter runs in this build)\", p);\n"
              "        return;\n"
              "    }\n\n", "ScriptState::run_script")
    s = _once(s, "    if (ImGui::CollapsingHeader(get_name().data())) {\n        if (m_last_online_match_state) {\n",
              "    if (ImGui::CollapsingHeader(get_name().data())) {\n"
              "        if (sdk::sf6::sf6bot_research_window()) {\n"
              "            ImGui::TextWrapped(\"%s: only reframework/autorun/sf6bot_state.lua (that exact file) runs, \"\n"
              "                               \"online included, until the date shown (UTC).\", sdk::sf6::sf6bot_research_text());\n"
              "        }\n\n"
              "        if (m_last_online_match_state) {\n", "ScriptRunner on_draw_ui")
    sr.write_text(s, encoding="utf-8")
    return {"until": day.isoformat(), "until_epoch": epoch, "exporter_bytes": len(data), "marker": marker}


if __name__ == "__main__":
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    info = patch(Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3]))
    for k, v in info.items():
        print(f"{k}: {v}")
